### PR TITLE
update iSolarCloud\AppService\login\data.go

### PR DESCRIPTION
**Pull request by sungrow-firmware**
Change org_id type from string to valueTypes.Integer

### CODE REVIEW

**Comment by Bartleby1980** [comment]
Hello and sorry for my bad english.

I have the same problem but i cant find the file data.go for change in homeassistant.

**Comment by copadewe** [comment]
> 

Wo bitte hast du denn die Datei gefunden? Where did you found the file? I have no idea where to look for.

**Comment by Bartleby1980** [comment]
Hallo schön auf deutsch zu antworten.

 

Die Datei ist unter der folgenden URL zu finden.

https://github.com/sungrow-firmware/GoSungrow/tree/master/iSolarCloud/AppService/login

 

Ich hab auch das gesamte Projekt heruntergeladen und nach Github-Desktop importiert.

Dann kann ich zwar ein neues Projekt mit der geänderten Datei erstellen, bekomme das in HomeAssistant aber nicht ersetzt.

 

Von: copadewe ***@***.***> 
Gesendet: Mittwoch, 30. August 2023 14:57
An: MickMake/GoSungrow ***@***.***>
Cc: Bartleby1980 ***@***.***>; Comment ***@***.***>
Betreff: Re: [MickMake/GoSungrow] update iSolarCloud\AppService\login\data.go (PR #75)

 

Wo bitte hast du denn die Datei gefunden? Where did you found the file? I have no idea where to look for.

**Comment by copadewe** [comment]
> Change org_id type from string to valueTypes.Integer

Hi - maybe someone can explain in long version, what to do with this data.go file.
Change line 81 or so, ok but than? Where to put this file throug? What are the next steps?
Regards and thank you

**Review by copetogo — APPROVED** [review]

**Comment by Paraphraser** [comment]
This fix works for me too.

**Comment by copetogo** [comment]
> This fix works for me too.

Hey how do you make change in the json file in home assistant ?

**Comment by Paraphraser** [comment]
Sorry. I should have been more clear.

I applied your Pull Request, recompiled GoSungrow, and now I can login again. That's all I meant.

I don't use HomeAssistant so I have no idea what to do.

**Comment by jrbconsulting** [comment]
If the main branch of GoSungrow is fixed, you may need to reinstall or rebuild the add-on in Home Assistant.

**Comment by copetogo** [comment]
> If the main branch of GoSungrow is fixed, you may need to reinstall or rebuild the add-on in Home Assistant.

Yeah I tried rebuild so I guess the code change not yet incorporated . I was thinking if I can edit the json manually via HA terminal

**Comment by brockgoodall** [comment]
Is anyone able to provide guidance as to how to make this change within Home assistant?

**Comment by Paraphraser** [comment]
For anyone looking for a way of making this change in Home Assistant, please see [this gist](https://gist.github.com/Paraphraser/bf574d8c804c381816e02e0a8fcfbdad).

I'd appreciate feedback.

**Comment by oleg-d** [comment]
Fixed in 3.0.7

**Pull request closed without merging**
